### ISSUE TITLE
[Feature Request] USB audio device

### ISSUE THREAD

**Issue by buldo** [TudbuT/picoAM#1]
Is it possible to use usb device mode to receive audio from pc via usb on overclocked rpi zero?

**Comment by TudbuT** [comment]
Most likely, but I don't know how USB audio works so im not qualified to add it at this moment.

**Comment by TudbuT** [comment]
I thought a bit: I think one might be able to stream the audio over UART, but I don't think it'll be very good quality, and it might be hard to transmit and receive fast enough.

**Comment by buldo** [comment]
My original idea was use tinyUSB. So rpi pico will act as usb sound card.
BTW, my feature request is more fun idea, than "I really need this and will use every day"

**Comment by TudbuT** [comment]
> My original idea was use tinyUSB. So rpi pico will act as usb sound card.

I guessed as such, but i don't know how to use tinyusb lol

**Comment by TudbuT** [comment]
Using USB to play audio is now supported by [pico_gpio](https://github.com/tudbut/pico_gpio) using the following command: 
```sh
( echo ; echo pwmfreq 1557000 ; echo audiostream 0 ; echo -en "\x80" ; pacat -r -d @DEFAULT_MONITOR@ --rate 111000 --format u8 --channels 1 --raw ) | pv -rK | picocom /dev/ttyACM0 -n
```
